name: mind_bridge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_analytics: ^11.3.6
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  path: ^1.8.1
  share_plus: ^10.1.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.14.2
  intl: ^0.20.2
  file_picker: ^8.1.6
  image_picker: ^1.0.0
  fluttertoast: ^8.0.9
  firebase_storage: ^12.3.7
  sign_button: ^2.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.1.4
  provider: ^6.0.3
  font_awesome_flutter: ^10.2.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.2.10+1
  connectivity_plus: ^6.1.1
  overlay_support: ^2.0.1
  velocity_x: ^4.1.0
  dio: ^5.2.1+1
  passwordfield: ^0.2.0
  lottie: ^3.3.0
  flutter_iconly: ^1.0.2
  iconsax: ^0.0.8
  flutter_quill: ^11.4.1
  dotted_border: ^2.0.0+3
  flutter_svg: ^2.0.7
  page_transition: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.21.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/animations/

flutter_native_splash:
  color: "#3367bf"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
    color: "#3367bf"
    icon_background_color: "#3367bf"
  web: false
  ios: false