name: mindbridge
description: A collaborative study platform for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^12.0.4

  provider: ^6.1.1

  file_picker: ^8.0.7
  image_picker: ^1.0.5

  google_fonts: ^6.1.0

  cached_network_image: ^3.3.0

  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  path_provider: ^2.1.1
  dio: ^5.4.1
  open_filex: ^4.5.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  dart_appwrite: ^14.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_web_auth_2: ^5.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png