// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATeyKbXg2AGhGX9JeVy1EQWSWZvQ-_-3o',
    appId: '1:503976714767:web:53a2a39688d50a2f87797a',
    messagingSenderId: '503976714767',
    projectId: 'mindbridge-3b93a',
    authDomain: 'mindbridge-3b93a.firebaseapp.com',
    storageBucket: 'mindbridge-3b93a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbamKkswHIg5rSHliht4AYHJ2kPcu0G0',
    appId: '1:503976714767:android:f21b8b545ce5993687797a',
    messagingSenderId: '503976714767',
    projectId: 'mindbridge-3b93a',
    storageBucket: 'mindbridge-3b93a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wixgtHiyK4LGNOs6LTvCjsRHIQ5jvQw',
    appId: '1:503976714767:ios:14b6f644952cb02487797a',
    messagingSenderId: '503976714767',
    projectId: 'mindbridge-3b93a',
    storageBucket: 'mindbridge-3b93a.firebasestorage.app',
    iosClientId: '503976714767-n83to8in4ojfq2nocdoddq9k1cppoai7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0wixgtHiyK4LGNOs6LTvCjsRHIQ5jvQw',
    appId: '1:503976714767:ios:14b6f644952cb02487797a',
    messagingSenderId: '503976714767',
    projectId: 'mindbridge-3b93a',
    storageBucket: 'mindbridge-3b93a.firebasestorage.app',
    iosClientId: '503976714767-n83to8in4ojfq2nocdoddq9k1cppoai7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATeyKbXg2AGhGX9JeVy1EQWSWZvQ-_-3o',
    appId: '1:503976714767:web:2dbbe20725ad3dae87797a',
    messagingSenderId: '503976714767',
    projectId: 'mindbridge-3b93a',
    authDomain: 'mindbridge-3b93a.firebaseapp.com',
    storageBucket: 'mindbridge-3b93a.firebasestorage.app',
  );
}
