// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFVOCdlKl6dJUqy7U4CElbhKCTS5XMis',
    appId: '1:486545882978:web:b6b33bb2c43245271b363b',
    messagingSenderId: '486545882978',
    projectId: 'mindbridge-8f2bc',
    authDomain: 'mindbridge-8f2bc.firebaseapp.com',
    storageBucket: 'mindbridge-8f2bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1L-SN6FlGigdtN87BHKBxt_CKSUHwLo',
    appId: '1:486545882978:android:df700cc916afa9c51b363b',
    messagingSenderId: '486545882978',
    projectId: 'mindbridge-8f2bc',
    storageBucket: 'mindbridge-8f2bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpV26C7OGTwXq6asyT7k_XDQldb0h2p4c',
    appId: '1:486545882978:ios:f65dc7c07f471db31b363b',
    messagingSenderId: '486545882978',
    projectId: 'mindbridge-8f2bc',
    storageBucket: 'mindbridge-8f2bc.firebasestorage.app',
    iosBundleId: 'com.example.mindBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpV26C7OGTwXq6asyT7k_XDQldb0h2p4c',
    appId: '1:486545882978:ios:f65dc7c07f471db31b363b',
    messagingSenderId: '486545882978',
    projectId: 'mindbridge-8f2bc',
    storageBucket: 'mindbridge-8f2bc.firebasestorage.app',
    iosBundleId: 'com.example.mindBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjFVOCdlKl6dJUqy7U4CElbhKCTS5XMis',
    appId: '1:486545882978:web:a6d2b6d4b7fc02661b363b',
    messagingSenderId: '486545882978',
    projectId: 'mindbridge-8f2bc',
    authDomain: 'mindbridge-8f2bc.firebaseapp.com',
    storageBucket: 'mindbridge-8f2bc.firebasestorage.app',
  );
}
